name: Deploy to Streamlit Cloud

on:
  push:
    branches: [main]
    paths:
      - 'app.py'
      - 'config.py'
      - 'llm_service.py'
      - 'requirements.txt'
      - 'setup.py'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit
          pip install -r requirements.txt
      
      - name: Deploy to Streamlit Cloud
        env:
          STREAMLIT_CLOUD_API_KEY: ${{ secrets.STREAMLIT_CLOUD_API_KEY }}
        run: |
          # This is a placeholder - actual deployment would use Streamlit Cloud's GitHub integration
          # or their CLI tool if available
          echo "Deployment would happen here with Streamlit Cloud API key"
          
          # For GitHub Pages deployment (alternative)
          # mkdir -p docs
          # echo "# DocuJudge" > docs/index.html
          # echo "This app is deployed on Streamlit Cloud" >> docs/index.html
          # echo "Check back later for updates!" >> docs/index.html
